const fs = require('fs');
const path = require('path');

const locales = ['en', 'tr', 'de'];
const basePath = path.join(__dirname, 'apps/frontend/messages');

const translations = {
  en: {
    "help.docs.admin.tickets_overview": {
      "title": "Ticket Pool",
      "desc": "The <strong>Support Tickets</strong> page collects all requests from customers in a single pool. You can manage statuses, assign agents, and prioritize tickets from here.",
      "pool_title": "Ticket Pool View",
      "pool_desc": "The ticket pool lists all active and past support requests. Manage your workload with filters and sorting options.",
      "pool_item1": "Filter by status, priority, company, and date range.",
      "pool_item2": "Select multiple tickets for bulk actions.",
      "pool_item3": "Tickets with SLA violations are marked with a red badge.",
      "status_title": "Changing Status",
      "status_desc": "You can change the status from the dropdown menu in the right panel on the ticket details page.",
      "status_item1_from": "New → Open",
      "status_item1_desc": "When you take the request for review",
      "status_item2_from": "Open → In Progress",
      "status_item2_desc": "When you actively start working on it",
      "status_item3_from": "In Progress → Solution Approval",
      "status_item3_desc": "When you provide a solution",
      "status_item4_from": "Solution Approval → Resolved",
      "status_item4_desc": "Automatically when the customer approves",
      "assignment_title": "Ticket Assignment",
      "assignment_desc": "You can assign the request to a specific expert agent using the <strong>Assign</strong> button on the ticket details page.",
      "assignment_item1": "The assigned agent receives an email notification.",
      "assignment_item2": "Assignments can be changed; past assignments are logged.",
      "tip_sla_desc": "SLA rules can automatically route unassigned tickets to the appropriate team. Configure SLA rules from the Team Management page."
    },
    "help.docs.admin.tickets_internal_notes": {
      "title": "Internal Notes & Assignment",
      "desc": "Internal notes allow you to communicate within the team without being visible to the customer. Route tickets to the right expert with the assignment feature.",
      "notes_title": "Adding an Internal Note",
      "step1_title": "1. Go to ticket details",
      "step1_desc": "Find the tabs above the reply box.",
      "step2_title": "2. Select the \"Internal Note\" tab",
      "step2_desc": "Switch to the <strong>Internal Note (Team Only)</strong> tab. Messages in this tab are invisible to the customer.",
      "step3_title": "3. Write and send the note",
      "step3_desc": "Write the information you want to convey to team members. Notes are marked with a yellow background, separating them from normal replies.",
      "tip_warning_title": "Attention",
      "tip_warning_desc": "Messages sent while in the internal note tab are not forwarded to the customer. Make sure to switch to the <strong>Reply</strong> tab to respond to the customer.",
      "workflow_title": "Ticket Assignment Workflow",
      "workflow_item1": "Click the <strong>Assign</strong> button on the right panel of the ticket details page.",
      "workflow_item2": "Select the appropriate agent from the dropdown list.",
      "workflow_item3": "The assigned agent receives an email notification and it appears in their ticket list.",
      "workflow_item4": "Assignment history is recorded in the ticket activity log."
    },
    "help.docs.admin.tickets_ai_copilot": {
      "title": "AI Co-Pilot",
      "desc": "AI Co-Pilot analyzes the customer's message, finds relevant documents from the Knowledge Pool, and prepares a professional reply draft.",
      "usage_title": "How to Use?",
      "step1_title": "Open ticket details",
      "step1_desc": "Open the support ticket you want to reply to.",
      "step2_title": "Click the \"Generate AI Draft\" button",
      "step2_desc": "Click the button in the top right corner. The AI process takes 5-10 seconds.",
      "step3_title": "Review the draft",
      "step3_desc": "AI presents the draft it prepared by scanning the customer's message and the Knowledge Pool. Source documents are listed at the bottom.",
      "step4_title": "Edit and send",
      "step4_desc": "Edit the draft according to your own style and send it to the customer.",
      "how_it_works_title": "How does AI Co-Pilot Work?",
      "how_item1": "The customer's message is matched with documents in the Knowledge Pool using vector search.",
      "how_item2": "The most relevant documents are used as context.",
      "how_item3": "A professional reply draft is generated and source documents are shown.",
      "tip_edit_title": "Always Edit the Draft",
      "tip_edit_desc": "AI drafts are a starting point. It is recommended that you edit it according to your own style and situation-specific details before sending it to the customer."
    },
    "help.docs.admin.team_teams": {
      "title": "Creating Teams",
      "desc": "Create your support departments (teams) and assign agents to the relevant teams. Teams ensure tickets are routed to the right experts.",
      "steps_title": "Team Creation Steps",
      "step1_title": "1. Go to the Team Management page",
      "step1_desc": "Click the <strong>Teams</strong> link from the left menu.",
      "step2_title": "2. Create a new team",
      "step2_desc": "Enter a team name and description (e.g. \"Allplan Technical Support\").",
      "step3_title": "3. Add agents",
      "step3_desc": "Select the agents to be included in the team. An agent can be in multiple teams.",
      "step4_title": "4. Configure SLA rules",
      "step4_desc": "Set the response time, resolution time, and business hours rules for the team.",
      "structure_title": "Team Structure Suggestions",
      "struct1_title": "Technical Support",
      "struct1_desc": "Allplan installation and error issues",
      "struct2_title": "License Management",
      "struct2_desc": "Activation and license transfers",
      "struct3_title": "Training",
      "struct3_desc": "Usage questions and training requests",
      "struct4_title": "General Support",
      "struct4_desc": "Uncategorized requests",
      "tip_auto_title": "Automatic Assignment",
      "tip_auto_desc": "When team and SLA rules are configured correctly, the system automatically assigns incoming tickets to the relevant team based on the product category."
    },
    "help.docs.admin.team_sla": {
      "title": "SLA Rule Configuration",
      "desc": "SLA (Service Level Agreement) rules define how quickly support requests must be responded to and resolved.",
      "params_title": "SLA Parameters",
      "param1_title": "First Response Time",
      "param1_desc": "The maximum time required for the first response after a ticket is opened.",
      "param1_example": "e.g., High priority → 2 hours",
      "param2_title": "Resolution Time",
      "param2_desc": "The maximum time required for the ticket to be completely resolved.",
      "param2_example": "e.g., Medium priority → 24 hours",
      "param3_title": "Business Hours",
      "param3_desc": "The time range during which the SLA timer will run. Can be paused outside business hours.",
      "param3_example": "e.g., Monday-Friday, 09:00-18:00",
      "priority_title": "Priority-Based SLA",
      "table_col1": "Priority",
      "table_col2": "First Response",
      "table_col3": "Resolution",
      "row1_pri": "Urgent",
      "row1_res": "1 hour",
      "row1_reso": "4 hours",
      "row2_pri": "High",
      "row2_res": "2 hours",
      "row2_reso": "8 hours",
      "row3_pri": "Medium",
      "row3_res": "4 hours",
      "row3_reso": "24 hours",
      "row4_pri": "Low",
      "row4_res": "8 hours",
      "row4_reso": "72 hours",
      "table_note": "* These values are sample configurations. Customize them from the Team Management page.",
      "violation_title": "SLA Violation Notifications",
      "vio_item1": "The system sends an automatic warning when the SLA time is about to expire.",
      "vio_item2": "Violated tickets are marked with a red <strong>SLA_VIO</strong> badge in the ticket list.",
      "vio_item3": "SLA violation statistics are displayed on the Dashboard.",
      "tip_hours_title": "Set Business Hours Correctly",
      "tip_hours_desc": "Configure business hours correctly so the SLA timer stops outside business hours. Otherwise, SLA violations may occur on weekends and holidays."
    }
  },
  tr: {
    "help.docs.admin.tickets_overview": {
      "title": "Bilet Havuzu",
      "desc": "<strong>Destek Talepleri</strong> sayfası, müşterilerden gelen tüm talepleri tek bir havuzda toplar. Durum yönetimi, atama ve önceliklendirme işlemlerini buradan gerçekleştirebilirsiniz.",
      "pool_title": "Bilet Havuzu Görünümü",
      "pool_desc": "Bilet havuzu, tüm aktif ve geçmiş destek taleplerini listeler. Filtreler ve sıralama seçenekleriyle iş yükünüzü yönetin.",
      "pool_item1": "Durum, öncelik, şirket ve tarih aralığına göre filtreleyin.",
      "pool_item2": "Toplu işlemler için birden fazla bilet seçin.",
      "pool_item3": "SLA ihlali olan biletler kırmızı rozet ile işaretlenir.",
      "status_title": "Durum Değiştirme",
      "status_desc": "Bilet detay sayfasında sağ paneldeki açılır menüden durumu değiştirebilirsiniz.",
      "status_item1_from": "Yeni → Açık",
      "status_item1_desc": "Talebi incelemeye aldığınızda",
      "status_item2_from": "Açık → İşlemde",
      "status_item2_desc": "Aktif olarak çalışmaya başladığınızda",
      "status_item3_from": "İşlemde → Çözüm Onayı",
      "status_item3_desc": "Çözüm sunduğunuzda",
      "status_item4_from": "Çözüm Onayı → Çözüldü",
      "status_item4_desc": "Müşteri onayladığında otomatik",
      "assignment_title": "Bilet Atama",
      "assignment_desc": "Bilet detay sayfasındaki <strong>Ata</strong> butonuyla talebi belirli bir uzman agent'a devredebilirsiniz.",
      "assignment_item1": "Atanan agent e-posta bildirimi alır.",
      "assignment_item2": "Atama değiştirilebilir; geçmiş atamalar loglanır.",
      "tip_sla_desc": "SLA kuralları, atanmamış biletleri otomatik olarak uygun ekibe yönlendirebilir. Ekip Yönetimi sayfasından SLA kurallarını yapılandırın."
    },
    "help.docs.admin.tickets_internal_notes": {
      "title": "İç Notlar & Atama",
      "desc": "İç notlar, müşteriye görünmeden ekip içi iletişim kurmanızı sağlar. Atama özelliği ile biletleri doğru uzmana yönlendirin.",
      "notes_title": "İç Not Ekleme",
      "step1_title": "1. Bilet detayına gidin",
      "step1_desc": "Yanıt kutusunun üstündeki sekmeleri bulun.",
      "step2_title": "2. \"İç Not\" sekmesini seçin",
      "step2_desc": "<strong>İç Not (Yalnızca Ekip)</strong> sekmesine geçin. Bu sekmedeki mesajlar müşteriye görünmez.",
      "step3_title": "3. Notu yazın ve gönderin",
      "step3_desc": "Ekip üyelerine iletmek istediğiniz bilgileri yazın. Notlar sarı arka planla işaretlenerek normal yanıtlardan ayrılır.",
      "tip_warning_title": "Dikkat",
      "tip_warning_desc": "İç not sekmesindeyken gönderilen mesajlar müşteriye iletilmez. Müşteriye yanıt vermek için <strong>Yanıt</strong> sekmesine geçtiğinizden emin olun.",
      "workflow_title": "Bilet Atama İş Akışı",
      "workflow_item1": "Bilet detay sayfasında sağ paneldeki <strong>Ata</strong> butonuna tıklayın.",
      "workflow_item2": "Açılan listeden uygun agent'ı seçin.",
      "workflow_item3": "Atanan agent e-posta bildirimi alır ve bilet listesinde görünür.",
      "workflow_item4": "Atama geçmişi bilet aktivite logunda kayıtlıdır."
    },
    "help.docs.admin.tickets_ai_copilot": {
      "title": "AI Co-Pilot",
      "desc": "AI Co-Pilot, müşteri mesajını analiz ederek Knowledge Pool'dan ilgili belgeleri bulur ve profesyonel bir yanıt taslağı hazırlar.",
      "usage_title": "Nasıl Kullanılır?",
      "step1_title": "Bilet detayına girin",
      "step1_desc": "Yanıtlamak istediğiniz destek talebini açın.",
      "step2_title": "\"AI Yanıt Taslağı Oluştur\" butonuna tıklayın",
      "step2_desc": "Sağ üst köşedeki butona tıklayın. AI işlemi 5-10 saniye sürer.",
      "step3_title": "Taslağı inceleyin",
      "step3_desc": "AI, müşteri mesajını ve Knowledge Pool'u tarayarak hazırladığı taslağı sunar. Kaynak belgeler altta listelenir.",
      "step4_title": "Düzenleyin ve gönderin",
      "step4_desc": "Taslağı kendi üslubunuza göre düzenleyin ve müşteriye gönderin.",
      "how_it_works_title": "AI Co-Pilot Nasıl Çalışır?",
      "how_item1": "Müşteri mesajı vektör aramasıyla Knowledge Pool'daki belgelerle eşleştirilir.",
      "how_item2": "En alakalı belgeler bağlam olarak kullanılır.",
      "how_item3": "Profesyonel bir yanıt taslağı oluşturulur ve kaynak belgeler gösterilir.",
      "tip_edit_title": "Taslağı Her Zaman Düzenleyin",
      "tip_edit_desc": "AI taslakları bir başlangıç noktasıdır. Müşteriye göndermeden önce kendi üslubunuza ve duruma özel detaylara göre düzenlemeniz önerilir."
    },
    "help.docs.admin.team_teams": {
      "title": "Ekip Oluşturma",
      "desc": "Destek departmanlarınızı (ekipleri) oluşturun ve agent'ları ilgili ekiplere atayın. Ekipler, biletlerin doğru uzmanlara yönlendirilmesini sağlar.",
      "steps_title": "Ekip Oluşturma Adımları",
      "step1_title": "1. Ekip Yönetimi sayfasına gidin",
      "step1_desc": "Sol menüden <strong>Ekipler</strong> bağlantısına tıklayın.",
      "step2_title": "2. Yeni ekip oluşturun",
      "step2_desc": "Ekip adı ve açıklaması girin (örn. \"Allplan Teknik Destek\").",
      "step3_title": "3. Agent'ları ekleyin",
      "step3_desc": "Ekibe dahil edilecek agent'ları seçin. Bir agent birden fazla ekipte yer alabilir.",
      "step4_title": "4. SLA kurallarını yapılandırın",
      "step4_desc": "Ekip için yanıt süresi, çözüm süresi ve mesai saati kurallarını belirleyin.",
      "structure_title": "Ekip Yapısı Önerileri",
      "struct1_title": "Teknik Destek",
      "struct1_desc": "Allplan kurulum ve hata sorunları",
      "struct2_title": "Lisans Yönetimi",
      "struct2_desc": "Aktivasyon ve lisans transferleri",
      "struct3_title": "Eğitim",
      "struct3_desc": "Kullanım soruları ve eğitim talepleri",
      "struct4_title": "Genel Destek",
      "struct4_desc": "Sınıflandırılamayan talepler",
      "tip_auto_title": "Otomatik Atama",
      "tip_auto_desc": "Ekip ve SLA kuralları doğru yapılandırıldığında, sistem gelen biletleri ürün kategorisine göre otomatik olarak ilgili ekibe atar."
    },
    "help.docs.admin.team_sla": {
      "title": "SLA Kural Yapılandırması",
      "desc": "SLA (Service Level Agreement) kuralları, destek taleplerine ne kadar sürede yanıt verilmesi ve çözülmesi gerektiğini tanımlar.",
      "params_title": "SLA Parametreleri",
      "param1_title": "İlk Yanıt Süresi",
      "param1_desc": "Bilet açıldıktan sonra ilk yanıtın verilmesi gereken maksimum süre.",
      "param1_example": "Örn: Yüksek öncelik → 2 saat",
      "param2_title": "Çözüm Süresi",
      "param2_desc": "Biletin tamamen çözülmesi gereken maksimum süre.",
      "param2_example": "Örn: Orta öncelik → 24 saat",
      "param3_title": "Mesai Saatleri",
      "param3_desc": "SLA sayacının çalışacağı saat aralığı. Mesai dışı duraklatılabilir.",
      "param3_example": "Örn: Pazartesi-Cuma, 09:00-18:00",
      "priority_title": "Öncelik Bazlı SLA",
      "table_col1": "Öncelik",
      "table_col2": "İlk Yanıt",
      "table_col3": "Çözüm",
      "row1_pri": "Acil",
      "row1_res": "1 saat",
      "row1_reso": "4 saat",
      "row2_pri": "Yüksek",
      "row2_res": "2 saat",
      "row2_reso": "8 saat",
      "row3_pri": "Orta",
      "row3_res": "4 saat",
      "row3_reso": "24 saat",
      "row4_pri": "Düşük",
      "row4_res": "8 saat",
      "row4_reso": "72 saat",
      "table_note": "* Bu değerler örnek yapılandırmadır. Ekip Yönetimi sayfasından özelleştirin.",
      "violation_title": "SLA İhlali Bildirimleri",
      "vio_item1": "SLA süresi dolmak üzereyken sistem otomatik uyarı gönderir.",
      "vio_item2": "İhlal olan biletler bilet listesinde kırmızı <strong>SLA_VIO</strong> rozeti ile işaretlenir.",
      "vio_item3": "Dashboard'da SLA ihlali istatistikleri görüntülenir.",
      "tip_hours_title": "Mesai Saatlerini Doğru Ayarlayın",
      "tip_hours_desc": "SLA sayacının mesai dışında durması için mesai saatlerini doğru yapılandırın. Aksi halde hafta sonu ve tatil günlerinde SLA ihlalleri oluşabilir."
    }
  },
  de: {
    "help.docs.admin.tickets_overview": {
      "title": "Ticket-Pool",
      "desc": "Die Seite <strong>Support-Tickets</strong> sammelt alle Kundenanfragen in einem Pool. Hier können Sie Status verwalten, Agenten zuweisen und Tickets priorisieren.",
      "pool_title": "Ticket-Pool-Ansicht",
      "pool_desc": "Der Ticketpool listet alle aktiven und vergangenen Supportanfragen auf. Verwalten Sie Ihre Arbeitslast mit Filtern und Sortieroptionen.",
      "pool_item1": "Nach Status, Priorität, Unternehmen und Zeitraum filtern.",
      "pool_item2": "Wählen Sie mehrere Tickets für Massenaktionen aus.",
      "pool_item3": "Tickets mit SLA-Verletzungen werden mit einem roten Abzeichen gekennzeichnet.",
      "status_title": "Status ändern",
      "status_desc": "Sie können den Status über das Dropdown-Menü im rechten Bereich auf der Ticket-Detailseite ändern.",
      "status_item1_from": "Neu → Offen",
      "status_item1_desc": "Wenn Sie die Anfrage zur Prüfung annehmen",
      "status_item2_from": "Offen → In Bearbeitung",
      "status_item2_desc": "Wenn Sie aktiv mit der Arbeit beginnen",
      "status_item3_from": "In Bearbeitung → Lösungsgenehmigung",
      "status_item3_desc": "Wenn Sie eine Lösung bereitstellen",
      "status_item4_from": "Lösungsgenehmigung → Gelöst",
      "status_item4_desc": "Automatisch, wenn der Kunde zustimmt",
      "assignment_title": "Ticket-Zuweisung",
      "assignment_desc": "Sie können die Anfrage einem bestimmten Experten über die Schaltfläche <strong>Zuweisen</strong> auf der Ticket-Detailseite zuweisen.",
      "assignment_item1": "Der zugewiesene Agent erhält eine E-Mail-Benachrichtigung.",
      "assignment_item2": "Zuweisungen können geändert werden; vergangene Zuweisungen werden protokolliert.",
      "tip_sla_desc": "SLA-Regeln können nicht zugewiesene Tickets automatisch an das entsprechende Team weiterleiten. Konfigurieren Sie SLA-Regeln auf der Seite Team-Management."
    },
    "help.docs.admin.tickets_internal_notes": {
      "title": "Interne Notizen & Zuweisung",
      "desc": "Interne Notizen ermöglichen es Ihnen, innerhalb des Teams zu kommunizieren, ohne für den Kunden sichtbar zu sein. Leiten Sie Tickets mit der Zuweisungsfunktion an den richtigen Experten weiter.",
      "notes_title": "Eine interne Notiz hinzufügen",
      "step1_title": "1. Gehen Sie zu den Ticketdetails",
      "step1_desc": "Suchen Sie die Registerkarten über dem Antwortfeld.",
      "step2_title": "2. Wählen Sie die Registerkarte \"Interne Notiz\"",
      "step2_desc": "Wechseln Sie zur Registerkarte <strong>Interne Notiz (nur Team)</strong>. Nachrichten in dieser Registerkarte sind für den Kunden unsichtbar.",
      "step3_title": "3. Notiz schreiben und senden",
      "step3_desc": "Schreiben Sie die Informationen, die Sie den Teammitgliedern übermitteln möchten. Notizen sind mit einem gelben Hintergrund markiert und von normalen Antworten getrennt.",
      "tip_warning_title": "Achtung",
      "tip_warning_desc": "Nachrichten, die in der Registerkarte \"Interne Notiz\" gesendet werden, werden nicht an den Kunden weitergeleitet. Stellen Sie sicher, dass Sie zur Registerkarte <strong>Antwort</strong> wechseln, um dem Kunden zu antworten.",
      "workflow_title": "Ticket-Zuweisungs-Workflow",
      "workflow_item1": "Klicken Sie im rechten Bereich der Ticket-Detailseite auf die Schaltfläche <strong>Zuweisen</strong>.",
      "workflow_item2": "Wählen Sie den entsprechenden Agenten aus der Dropdown-Liste aus.",
      "workflow_item3": "Der zugewiesene Agent erhält eine E-Mail-Benachrichtigung und sie wird in seiner Ticketliste angezeigt.",
      "workflow_item4": "Der Zuweisungsverlauf wird im Ticketaktivitätsprotokoll aufgezeichnet."
    },
    "help.docs.admin.tickets_ai_copilot": {
      "title": "KI-Copilot",
      "desc": "Der KI-Copilot analysiert die Nachricht des Kunden, findet relevante Dokumente aus dem Knowledge Pool und erstellt einen professionellen Antwortentwurf.",
      "usage_title": "Wie benutzt man?",
      "step1_title": "Ticketdetails öffnen",
      "step1_desc": "Öffnen Sie das Support-Ticket, auf das Sie antworten möchten.",
      "step2_title": "Klicken Sie auf die Schaltfläche \"KI-Entwurf generieren\"",
      "step2_desc": "Klicken Sie auf die Schaltfläche oben rechts. Der KI-Prozess dauert 5-10 Sekunden.",
      "step3_title": "Überprüfen Sie den Entwurf",
      "step3_desc": "Die KI präsentiert den Entwurf, den sie durch Scannen der Kundenmitteilung und des Knowledge Pools vorbereitet hat. Quelldokumente sind unten aufgeführt.",
      "step4_title": "Bearbeiten und Senden",
      "step4_desc": "Bearbeiten Sie den Entwurf nach Ihrem eigenen Stil und senden Sie ihn an den Kunden.",
      "how_it_works_title": "Wie funktioniert der KI-Copilot?",
      "how_item1": "Die Kundenmitteilung wird per Vektorsuche mit Dokumenten im Knowledge Pool abgeglichen.",
      "how_item2": "Die relevantesten Dokumente werden als Kontext verwendet.",
      "how_item3": "Ein professioneller Antwortentwurf wird erstellt und Quelldokumente werden angezeigt.",
      "tip_edit_title": "Entwurf immer bearbeiten",
      "tip_edit_desc": "KI-Entwürfe sind ein Ausgangspunkt. Es wird empfohlen, sie nach Ihrem eigenen Stil und den situationsspezifischen Details zu bearbeiten, bevor Sie sie an den Kunden senden."
    },
    "help.docs.admin.team_teams": {
      "title": "Teams erstellen",
      "desc": "Erstellen Sie Ihre Supportabteilungen (Teams) und weisen Sie den entsprechenden Teams Agenten zu. Teams stellen sicher, dass Tickets an die richtigen Experten weitergeleitet werden.",
      "steps_title": "Schritte zur Teamerstellung",
      "step1_title": "1. Gehen Sie zur Team-Management-Seite",
      "step1_desc": "Klicken Sie im linken Menü auf den Link <strong>Teams</strong>.",
      "step2_title": "2. Neues Team erstellen",
      "step2_desc": "Geben Sie einen Teamnamen und eine Beschreibung ein (z. B. \"Allplan Technischer Support\").",
      "step3_title": "3. Agenten hinzufügen",
      "step3_desc": "Wählen Sie die Agenten aus, die dem Team hinzugefügt werden sollen. Ein Agent kann mehreren Teams angehören.",
      "step4_title": "4. SLA-Regeln konfigurieren",
      "step4_desc": "Legen Sie die Reaktionszeit, Lösungszeit und Geschäftszeiten für das Team fest.",
      "structure_title": "Vorschläge für Teamstrukturen",
      "struct1_title": "Technischer Support",
      "struct1_desc": "Allplan-Installations- und Fehlerprobleme",
      "struct2_title": "Lizenzverwaltung",
      "struct2_desc": "Aktivierung und Lizenzübertragungen",
      "struct3_title": "Training",
      "struct3_desc": "Nutzungsfragen und Schulungsanfragen",
      "struct4_title": "Allgemeiner Support",
      "struct4_desc": "Nicht kategorisierte Anfragen",
      "tip_auto_title": "Automatische Zuweisung",
      "tip_auto_desc": "Wenn Team- und SLA-Regeln korrekt konfiguriert sind, weist das System eingehende Tickets basierend auf der Produktkategorie automatisch dem entsprechenden Team zu."
    },
    "help.docs.admin.team_sla": {
      "title": "SLA-Regel-Konfiguration",
      "desc": "SLA-Regeln (Service Level Agreement) definieren, wie schnell Supportanfragen beantwortet und behoben werden müssen.",
      "params_title": "SLA-Parameter",
      "param1_title": "Erste Reaktionszeit",
      "param1_desc": "Die maximale Zeit, die für die erste Antwort nach der Eröffnung eines Tickets erforderlich ist.",
      "param1_example": "z. B. Hohe Priorität → 2 Stunden",
      "param2_title": "Lösungszeit",
      "param2_desc": "Die maximale Zeit, die für die vollständige Lösung des Tickets erforderlich ist.",
      "param2_example": "z. B. Mittlere Priorität → 24 Stunden",
      "param3_title": "Geschäftszeiten",
      "param3_desc": "Der Zeitraum, in dem der SLA-Timer läuft. Kann außerhalb der Geschäftszeiten angehalten werden.",
      "param3_example": "z. B. Montag-Freitag, 09:00-18:00",
      "priority_title": "Prioritätsbasiertes SLA",
      "table_col1": "Priorität",
      "table_col2": "Erste Antwort",
      "table_col3": "Lösung",
      "row1_pri": "Dringend",
      "row1_res": "1 Stunde",
      "row1_reso": "4 Stunden",
      "row2_pri": "Hoch",
      "row2_res": "2 Stunden",
      "row2_reso": "8 Stunden",
      "row3_pri": "Mittel",
      "row3_res": "4 Stunden",
      "row3_reso": "24 Stunden",
      "row4_pri": "Niedrig",
      "row4_res": "8 Stunden",
      "row4_reso": "72 Stunden",
      "table_note": "* Diese Werte sind Beispielkonfigurationen. Passen Sie sie auf der Seite Team-Management an.",
      "violation_title": "SLA-Verstoßbenachrichtigungen",
      "vio_item1": "Das System sendet eine automatische Warnung, wenn die SLA-Zeit abläuft.",
      "vio_item2": "Verletzte Tickets werden in der Ticketliste mit einem roten <strong>SLA_VIO</strong>-Abzeichen markiert.",
      "vio_item3": "SLA-Verletzungsstatistiken werden auf dem Dashboard angezeigt.",
      "tip_hours_title": "Geschäftszeiten richtig einstellen",
      "tip_hours_desc": "Konfigurieren Sie die Geschäftszeiten richtig, damit der SLA-Timer außerhalb der Geschäftszeiten stoppt. Andernfalls können an Wochenenden und Feiertagen SLA-Verletzungen auftreten."
    }
  }
};

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] instanceof Object && key in target) {
      Object.assign(source[key], deepMerge(target[key], source[key]));
    }
  }
  Object.assign(target || {}, source);
  return target;
}

function unflatten(data) {
  const result = {};
  for (const key in data) {
    const keys = key.split('.');
    keys.reduce((acc, currentKey, index) => {
      if (index === keys.length - 1) {
        acc[currentKey] = data[key];
      } else {
        acc[currentKey] = acc[currentKey] || {};
      }
      return acc[currentKey];
    }, result);
  }
  return result;
}

for (const locale of locales) {
  const filePath = path.join(basePath, `${locale}.json`);
  const currentContent = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const newTranslations = unflatten(translations[locale]);
  
  const updatedContent = deepMerge(currentContent, newTranslations);
  fs.writeFileSync(filePath, JSON.stringify(updatedContent, null, 2));
  console.log(`Updated ${locale}.json`);
}
