const fs = require('fs');
const path = require('path');

const locales = ['en', 'tr', 'de'];
const basePath = path.join(__dirname, 'apps/frontend/messages');

const translations = {
  en: {
    "help.docs.customer.my_tickets_create": {
      "title": "Create New Support Ticket",
      "desc": "To communicate your issue to the support team, you can create a new record from the <strong>My Tickets</strong> page.",
      "tip_ai_title": "Try AI Assistant First",
      "tip_ai_desc": "Before opening a ticket, try solving your issue with the <strong>AI Assistant</strong>. Most technical issues can be answered in minutes.",
      "steps_title": "Step-by-Step Ticket Creation",
      "step1_title": "Product Selection",
      "step1_desc": "After clicking the \"New Ticket\" button, select the product family you are experiencing issues with (e.g. ALLPLAN, AX3000). This ensures your request is routed directly to the relevant expert team.",
      "step2_title": "Subject and Details",
      "step2_desc": "Enter a clear title and details describing the issue you encountered. Select the urgency level (determined by SLA).",
      "step3_title": "File Attachments",
      "step3_desc": "You can upload files up to <strong>25 MB</strong> using drag-and-drop.",
      "step4_title": "System Info (Hotinfo)",
      "step4_desc": "For Allplan errors, a system information file (.hxl) is required. If you have Hotinfo saved on your profile, it is automatically attached.",
      "tip_crash_title": "For Allplan Crashes",
      "tip_crash_desc": "In case of crashes, attach the <strong>.hxl Hotinfo</strong> and <strong>.dmp crash dump</strong> files from the <code>%AppData%\\Nemetschek\\Allplan</code> directory. This significantly speeds up diagnosis.",
      "step5_title": "Submit Ticket",
      "step5_desc": "Click the \"Create Ticket\" button. You will receive an email notification when your ticket is created.",
      "priorities_title": "Priority Levels",
      "priority_low": "General questions, feature requests",
      "priority_medium": "Issues affecting workflow",
      "priority_high": "Critical business processes stopped",
      "priority_urgent": "System is completely unusable"
    },
    "help.docs.customer.my_tickets_attachments": {
      "title": "File Attachments",
      "desc": "You can attach files up to <strong>25 MB</strong> to your support ticket using drag-and-drop. Below are the accepted and rejected file types.",
      "accepted_title": "Accepted File Types",
      "category": "Category",
      "extensions": "Extensions",
      "note": "Note",
      "acc_cat1": "Images",
      "acc_note1": "Screenshots, error dialogs",
      "acc_cat2": "Documents",
      "acc_note2": "Technical documents, reports",
      "acc_cat3": "Archives",
      "acc_note3": "To bundle multiple log files",
      "acc_cat4": "Diagnostic Files",
      "acc_note4": "Allplan Hotinfo and crash dump",
      "acc_cat5": "Video",
      "acc_note5": "For crash or bug reproduction",
      "rejected_title": "Rejected File Types",
      "rej_note1": "Executable files",
      "rej_note2": "Script and image files",
      "rej_warning": "These file types are blocked for security reasons.",
      "tip_crash_title": "For Allplan Crashes",
      "tip_crash_desc": "For Allplan crashes, attaching the <strong>.hxl Hotinfo</strong> file and <strong>.dmp crash dump</strong> file from the <code>%AppData%\\Nemetschek\\Allplan</code> directory speeds up diagnosis significantly."
    },
    "help.docs.customer.my_tickets_tracking": {
      "title": "Ticket Tracking",
      "desc": "You can track the support tickets you created in real-time from the <strong>My Tickets</strong> page.",
      "status_title": "Ticket Statuses",
      "stat_new": "New",
      "stat_new_desc": "Your request has been received, not yet reviewed.",
      "stat_open": "Open",
      "stat_open_desc": "The support team is reviewing your request.",
      "stat_in_progress": "In Progress",
      "stat_in_progress_desc": "An expert is actively working on it.",
      "stat_waiting": "Waiting for Customer",
      "stat_waiting_desc": "The team is waiting for additional information from you.",
      "stat_solution": "Solution Approval",
      "stat_solution_desc": "A solution has been provided, awaiting your approval.",
      "stat_resolved": "Resolved",
      "stat_resolved_desc": "The issue has been resolved and closed.",
      "stat_closed": "Closed",
      "stat_closed_desc": "The request has been completed and archived.",
      "approval_title": "Approving a Solution",
      "app_step1_title": "When a Solution Proposal Arrives",
      "app_step1_desc": "When the support team offers a solution, the ticket status changes to <strong>Solution Approval</strong>. An email notification is sent to you.",
      "app_step2_title": "Approving or Rejecting",
      "app_step2_desc": "On the ticket details page, you can mark the solution as <strong>Approve</strong> or <strong>Insufficient, Waiting for Details</strong>.",
      "csat_title": "Satisfaction Score (CSAT)",
      "csat_desc": "After the ticket is closed, you can give a satisfaction score between 1-5 stars. This feedback contributes to the AI's learning process.",
      "tip_csat_title": "Give 5 Stars",
      "tip_csat_desc": "5-star solutions are marked as learning candidates by the AI and can be used as automatic responses for similar future issues."
    },
    "help.docs.customer.knowledge_base_overview": {
      "title": "Knowledge Base",
      "desc": "The Knowledge Base is the corporate memory center containing solutions to common problems, how-to guides, and technical documents.",
      "search_title": "Searching the Knowledge Base",
      "search_step1_title": "1. Go to the Knowledge Base page",
      "search_step1_desc": "Click the <strong>Knowledge Base</strong> link in the left menu.",
      "search_step2_title": "2. Perform a search",
      "search_step2_desc": "Enter keywords in the search box at the top. The system performs a full-text search on titles and content.",
      "search_step3_title": "3. Read the article",
      "search_step3_desc": "Click on the relevant article to access the step-by-step solution guide.",
      "types_title": "Article Types",
      "type1_title": "How-To",
      "type1_desc": "Step-by-step operation guides",
      "type2_title": "Troubleshooting",
      "type2_desc": "Error messages and solutions",
      "type3_title": "Reference",
      "type3_desc": "Technical specifications and parameters",
      "type4_title": "Training",
      "type4_desc": "Feature usage guides",
      "statuses_title": "Article Statuses",
      "stat1": "Active",
      "stat1_desc": "Approved and up-to-date articles",
      "stat2": "Draft",
      "stat2_desc": "Unpublished content",
      "stat3": "Archived",
      "stat3_desc": "Outdated old articles",
      "tip_ai_title": "Search with AI",
      "tip_ai_desc": "If you cannot find what you are looking for in the knowledge base, use the <strong>AI Assistant</strong>. AI semantically scans the knowledge base and generates answers in a broader context."
    },
    "help.docs.customer.profile_settings": {
      "title": "Profile & Settings",
      "desc": "Update your personal information, change your password, and manage your notification preferences.",
      "update_title": "Updating Profile Information",
      "update_step1_title": "1. Go to the profile page",
      "update_step1_desc": "Click the <strong>My Profile</strong> link at the bottom of the left menu.",
      "update_step2_title": "2. Edit information",
      "update_step2_desc": "You can update information such as name, surname, phone number, and job title.",
      "update_step3_title": "3. Save",
      "update_step3_desc": "Apply your changes by clicking the <strong>Save</strong> button.",
      "password_title": "Changing Password",
      "pass_item1": "Go to the <strong>Change Password</strong> section on your profile page.",
      "pass_item2": "Enter your current password and your new password.",
      "pass_item3": "Your new password must be at least 8 characters long.",
      "hotinfo_title": "System Info (Hotinfo)",
      "hotinfo_desc": "Your profile page holds your registered system info (Hotinfo) file. This file is automatically attached when creating a support ticket.",
      "hotinfo_item1": "Upload the <strong>.hxl</strong> file exported from Allplan.",
      "hotinfo_item2": "Keeping the system info up-to-date speeds up the support process.",
      "tip_email_title": "Keep Your Email Address Up-to-Date",
      "tip_email_desc": "Support ticket notifications and announcements are sent to your registered email address. Ensure your email address is correct."
    }
  },
  tr: {
    "help.docs.customer.my_tickets_create": {
      "title": "Yeni Destek Talebi Oluşturma",
      "desc": "Sorununuzu destek ekibine iletmek için <strong>Destek Taleplerim</strong> sayfasından yeni bir kayıt oluşturabilirsiniz.",
      "tip_ai_title": "Önce AI Asistanını Deneyin",
      "tip_ai_desc": "Destek talebi açmadan önce <strong>AI Asistanı</strong> ile sorununuzu çözmeyi deneyin. Çoğu teknik sorun birkaç dakika içinde yanıtlanabilir.",
      "steps_title": "Adım Adım Talep Oluşturma",
      "step1_title": "Ürün Seçimi",
      "step1_desc": "\"Yeni Talep\" butonuna tıkladıktan sonra sorun yaşadığınız ürün ailesini seçin (örn. ALLPLAN, AX3000). Bu sayede talebiniz doğrudan ilgili uzman ekibine yönlendirilir.",
      "step2_title": "Konu ve Detaylar",
      "step2_desc": "Karşılaştığınız sorunu açıklayan net bir başlık ve detay girin. Aciliyet seviyesini seçin (SLA tarafından belirlenir).",
      "step3_title": "Dosya Ekleri",
      "step3_desc": "Sürükle-bırak ile <strong>25 MB</strong>'a kadar dosya yükleyebilirsiniz.",
      "step4_title": "Sistem Bilgisi (Hotinfo)",
      "step4_desc": "Allplan hataları için sistem bilgisi dosyası (.hxl) gereklidir. Profil sayfanızda kayıtlı Hotinfo varsa otomatik olarak eklenir.",
      "tip_crash_title": "Allplan Çökmeleri İçin",
      "tip_crash_desc": "Çökme durumlarında <code>%AppData%\\Nemetschek\\Allplan</code> dizinindeki <strong>.hxl Hotinfo</strong> ve <strong>.dmp crash dump</strong> dosyalarını ekleyin. Bu, teşhisi önemli ölçüde hızlandırır.",
      "step5_title": "Talebi Gönderin",
      "step5_desc": "\"Talep Oluştur\" butonuna tıklayın. Talebiniz oluşturulduğunda e-posta ile bildirim alırsınız.",
      "priorities_title": "Öncelik Seviyeleri",
      "priority_low": "Genel sorular, özellik istekleri",
      "priority_medium": "İş akışını etkileyen sorunlar",
      "priority_high": "Kritik iş süreçleri durdu",
      "priority_urgent": "Sistem tamamen kullanılamıyor"
    },
    "help.docs.customer.my_tickets_attachments": {
      "title": "Dosya Ekleri",
      "desc": "Destek talebinize sürükle-bırak ile <strong>25 MB</strong>'a kadar dosya ekleyebilirsiniz. Aşağıda kabul edilen ve reddedilen dosya türleri listelenmiştir.",
      "accepted_title": "Kabul Edilen Dosya Türleri",
      "category": "Kategori",
      "extensions": "Uzantılar",
      "note": "Not",
      "acc_cat1": "Görseller",
      "acc_note1": "Ekran görüntüleri, hata diyalogları",
      "acc_cat2": "Belgeler",
      "acc_note2": "Teknik dökümanlar, raporlar",
      "acc_cat3": "Arşivler",
      "acc_note3": "Birden fazla log dosyasını paketlemek için",
      "acc_cat4": "Tanılama Dosyaları",
      "acc_note4": "Allplan Hotinfo ve crash dump",
      "acc_cat5": "Video",
      "acc_note5": "Çökme veya hata yeniden üretimi için",
      "rejected_title": "Reddedilen Dosya Türleri",
      "rej_note1": "Çalıştırılabilir dosyalar",
      "rej_note2": "Script ve imaj dosyaları",
      "rej_warning": "Bu dosya türleri güvenlik nedeniyle engellenmektedir.",
      "tip_crash_title": "Allplan Çökmeleri İçin",
      "tip_crash_desc": "Allplan çökmelerinde <code>%AppData%\\Nemetschek\\Allplan</code> dizinindeki <strong>.hxl Hotinfo</strong> dosyasını ve <strong>.dmp crash dump</strong> dosyasını eklemeniz teşhisi önemli ölçüde hızlandırır."
    },
    "help.docs.customer.my_tickets_tracking": {
      "title": "Talep Takibi",
      "desc": "Oluşturduğunuz destek taleplerini <strong>Destek Taleplerim</strong> sayfasından anlık olarak takip edebilirsiniz.",
      "status_title": "Talep Durumları",
      "stat_new": "Yeni",
      "stat_new_desc": "Talebiniz alındı, henüz incelenmedi.",
      "stat_open": "Açık",
      "stat_open_desc": "Destek ekibi talebinizi inceliyor.",
      "stat_in_progress": "İşlemde",
      "stat_in_progress_desc": "Uzman tarafından aktif olarak çalışılıyor.",
      "stat_waiting": "Müşteri Bekliyor",
      "stat_waiting_desc": "Ekip sizden ek bilgi bekliyor.",
      "stat_solution": "Çözüm Onayı",
      "stat_solution_desc": "Çözüm sunuldu, onayınız bekleniyor.",
      "stat_resolved": "Çözüldü",
      "stat_resolved_desc": "Sorun çözüldü ve kapatıldı.",
      "stat_closed": "Kapalı",
      "stat_closed_desc": "Talep tamamlandı ve arşivlendi.",
      "approval_title": "Çözüm Onaylama",
      "app_step1_title": "Çözüm Önerisi Geldiğinde",
      "app_step1_desc": "Destek ekibi bir çözüm sunduğunda talep <strong>Çözüm Onayı</strong> durumuna geçer. Size e-posta bildirimi gönderilir.",
      "app_step2_title": "Onaylama veya Reddetme",
      "app_step2_desc": "Talep detay sayfasında çözümü <strong>Onayla</strong> veya <strong>Yetersiz, Detay Bekliyorum</strong> olarak işaretleyebilirsiniz.",
      "csat_title": "Memnuniyet Puanı (CSAT)",
      "csat_desc": "Talep kapatıldıktan sonra 1-5 yıldız arasında memnuniyet puanı verebilirsiniz. Bu geri bildirimler AI'ın öğrenme sürecine katkı sağlar.",
      "tip_csat_title": "5 Yıldız Verin",
      "tip_csat_desc": "5 yıldızlı çözümler AI tarafından öğrenme adayı olarak işaretlenir ve gelecekteki benzer sorunlarda otomatik yanıt olarak kullanılabilir."
    },
    "help.docs.customer.knowledge_base_overview": {
      "title": "Bilgi Bankası",
      "desc": "Bilgi Bankası, sık karşılaşılan sorunların çözümlerini, nasıl yapılır kılavuzlarını ve teknik belgeleri içeren kurumsal hafıza merkezidir.",
      "search_title": "Bilgi Bankasında Arama",
      "search_step1_title": "1. Bilgi Bankası sayfasına gidin",
      "search_step1_desc": "Sol menüden <strong>Bilgi Bankası</strong> bağlantısına tıklayın.",
      "search_step2_title": "2. Arama yapın",
      "search_step2_desc": "Üst kısımdaki arama kutusuna anahtar kelimeler girin. Sistem başlık ve içerik üzerinde tam metin araması yapar.",
      "search_step3_title": "3. Makaleyi okuyun",
      "search_step3_desc": "İlgili makaleye tıklayarak adım adım çözüm kılavuzuna ulaşın.",
      "types_title": "Makale Türleri",
      "type1_title": "Nasıl Yapılır",
      "type1_desc": "Adım adım işlem kılavuzları",
      "type2_title": "Sorun Giderme",
      "type2_desc": "Hata mesajları ve çözümleri",
      "type3_title": "Referans",
      "type3_desc": "Teknik özellikler ve parametreler",
      "type4_title": "Eğitim",
      "type4_desc": "Özellik kullanım rehberleri",
      "statuses_title": "Makale Durumları",
      "stat1": "Aktif",
      "stat1_desc": "Onaylanmış ve güncel makaleler",
      "stat2": "Taslak",
      "stat2_desc": "Henüz yayınlanmamış içerikler",
      "stat3": "Arşiv",
      "stat3_desc": "Güncelliğini yitirmiş eski makaleler",
      "tip_ai_title": "AI ile Arama",
      "tip_ai_desc": "Bilgi bankasında aradığınızı bulamazsanız <strong>AI Asistanı</strong>'nı kullanın. AI, bilgi bankasını semantik olarak tarar ve daha geniş bir bağlamda yanıt üretir."
    },
    "help.docs.customer.profile_settings": {
      "title": "Profil & Ayarlar",
      "desc": "Kişisel bilgilerinizi güncelleyin, şifrenizi değiştirin ve bildirim tercihlerinizi yönetin.",
      "update_title": "Profil Bilgilerini Güncelleme",
      "update_step1_title": "1. Profil sayfasına gidin",
      "update_step1_desc": "Sol menünün alt kısmındaki <strong>Profilim</strong> bağlantısına tıklayın.",
      "update_step2_title": "2. Bilgileri düzenleyin",
      "update_step2_desc": "Ad, soyad, telefon numarası ve iş unvanı gibi bilgileri güncelleyebilirsiniz.",
      "update_step3_title": "3. Kaydedin",
      "update_step3_desc": "<strong>Kaydet</strong> butonuna tıklayarak değişikliklerinizi uygulayın.",
      "password_title": "Şifre Değiştirme",
      "pass_item1": "Profil sayfasındaki <strong>Şifre Değiştir</strong> bölümüne gidin.",
      "pass_item2": "Mevcut şifrenizi ve yeni şifrenizi girin.",
      "pass_item3": "Yeni şifreniz en az 8 karakter uzunluğunda olmalıdır.",
      "hotinfo_title": "Sistem Bilgisi (Hotinfo)",
      "hotinfo_desc": "Profil sayfanızda kayıtlı sistem bilgisi (Hotinfo) dosyanız bulunur. Bu dosya, destek talebi oluştururken otomatik olarak eklenir.",
      "hotinfo_item1": "Allplan'dan dışa aktarılan <strong>.hxl</strong> dosyasını yükleyin.",
      "hotinfo_item2": "Sistem bilgisi güncel tutulduğunda destek süreci hızlanır.",
      "tip_email_title": "E-posta Adresinizi Güncel Tutun",
      "tip_email_desc": "Destek talebi bildirimleri ve duyurular kayıtlı e-posta adresinize gönderilir. E-posta adresinizin doğru olduğundan emin olun."
    }
  },
  de: {
    "help.docs.customer.my_tickets_create": {
      "title": "Neues Support-Ticket erstellen",
      "desc": "Um Ihr Problem dem Support-Team mitzuteilen, können Sie auf der Seite <strong>Meine Tickets</strong> einen neuen Datensatz erstellen.",
      "tip_ai_title": "Probieren Sie zuerst den KI-Assistenten",
      "tip_ai_desc": "Versuchen Sie, Ihr Problem mit dem <strong>KI-Assistenten</strong> zu lösen, bevor Sie ein Ticket eröffnen. Die meisten technischen Probleme können innerhalb von Minuten beantwortet werden.",
      "steps_title": "Schritt-für-Schritt-Ticketerstellung",
      "step1_title": "Produktauswahl",
      "step1_desc": "Wählen Sie nach Klick auf die Schaltfläche \"Neues Ticket\" die Produktfamilie aus, bei der Probleme auftreten (z. B. ALLPLAN, AX3000). Dadurch wird sichergestellt, dass Ihre Anfrage direkt an das zuständige Expertenteam weitergeleitet wird.",
      "step2_title": "Betreff und Details",
      "step2_desc": "Geben Sie einen klaren Titel und Details ein, die das aufgetretene Problem beschreiben. Wählen Sie die Dringlichkeitsstufe (vom SLA bestimmt).",
      "step3_title": "Dateianhänge",
      "step3_desc": "Sie können Dateien bis zu <strong>25 MB</strong> per Drag-and-Drop hochladen.",
      "step4_title": "Systeminfo (Hotinfo)",
      "step4_desc": "Für Allplan-Fehler ist eine Systeminformationsdatei (.hxl) erforderlich. Wenn in Ihrem Profil Hotinfo gespeichert ist, wird diese automatisch angehängt.",
      "tip_crash_title": "Für Allplan-Abstürze",
      "tip_crash_desc": "Fügen Sie bei Abstürzen die <strong>.hxl Hotinfo</strong>- und <strong>.dmp Crash-Dump</strong>-Dateien aus dem Verzeichnis <code>%AppData%\\Nemetschek\\Allplan</code> bei. Dies beschleunigt die Diagnose erheblich.",
      "step5_title": "Ticket senden",
      "step5_desc": "Klicken Sie auf die Schaltfläche \"Ticket erstellen\". Sie erhalten eine E-Mail-Benachrichtigung, wenn Ihr Ticket erstellt wurde.",
      "priorities_title": "Prioritätsstufen",
      "priority_low": "Allgemeine Fragen, Funktionswünsche",
      "priority_medium": "Probleme, die den Arbeitsablauf beeinträchtigen",
      "priority_high": "Kritische Geschäftsprozesse gestoppt",
      "priority_urgent": "System ist völlig unbrauchbar"
    },
    "help.docs.customer.my_tickets_attachments": {
      "title": "Dateianhänge",
      "desc": "Sie können Ihrem Support-Ticket per Drag-and-Drop Dateien von bis zu <strong>25 MB</strong> hinzufügen. Unten sind die akzeptierten und abgelehnten Dateitypen aufgeführt.",
      "accepted_title": "Akzeptierte Dateitypen",
      "category": "Kategorie",
      "extensions": "Erweiterungen",
      "note": "Hinweis",
      "acc_cat1": "Bilder",
      "acc_note1": "Screenshots, Fehlerdialoge",
      "acc_cat2": "Dokumente",
      "acc_note2": "Technische Dokumente, Berichte",
      "acc_cat3": "Archive",
      "acc_note3": "Um mehrere Protokolldateien zu bündeln",
      "acc_cat4": "Diagnosedateien",
      "acc_note4": "Allplan Hotinfo und Crash Dump",
      "acc_cat5": "Video",
      "acc_note5": "Zur Reproduktion von Abstürzen oder Fehlern",
      "rejected_title": "Abgelehnte Dateitypen",
      "rej_note1": "Ausführbare Dateien",
      "rej_note2": "Skript- und Imagedateien",
      "rej_warning": "Diese Dateitypen werden aus Sicherheitsgründen blockiert.",
      "tip_crash_title": "Für Allplan-Abstürze",
      "tip_crash_desc": "Bei Allplan-Abstürzen beschleunigt das Anhängen der Datei <strong>.hxl Hotinfo</strong> und der Datei <strong>.dmp Crash Dump</strong> aus dem Verzeichnis <code>%AppData%\\Nemetschek\\Allplan</code> die Diagnose erheblich."
    },
    "help.docs.customer.my_tickets_tracking": {
      "title": "Ticket-Verfolgung",
      "desc": "Sie können die von Ihnen erstellten Support-Tickets auf der Seite <strong>Meine Tickets</strong> in Echtzeit verfolgen.",
      "status_title": "Ticket-Status",
      "stat_new": "Neu",
      "stat_new_desc": "Ihre Anfrage ist eingegangen und noch nicht überprüft.",
      "stat_open": "Offen",
      "stat_open_desc": "Das Support-Team prüft Ihre Anfrage.",
      "stat_in_progress": "In Bearbeitung",
      "stat_in_progress_desc": "Ein Experte arbeitet aktiv daran.",
      "stat_waiting": "Warten auf Kunde",
      "stat_waiting_desc": "Das Team wartet auf zusätzliche Informationen von Ihnen.",
      "stat_solution": "Lösungsgenehmigung",
      "stat_solution_desc": "Eine Lösung wurde bereitgestellt, wartet auf Ihre Genehmigung.",
      "stat_resolved": "Gelöst",
      "stat_resolved_desc": "Das Problem wurde behoben und geschlossen.",
      "stat_closed": "Geschlossen",
      "stat_closed_desc": "Die Anfrage wurde abgeschlossen und archiviert.",
      "approval_title": "Eine Lösung genehmigen",
      "app_step1_title": "Wenn ein Lösungsvorschlag eintrifft",
      "app_step1_desc": "Wenn das Support-Team eine Lösung anbietet, ändert sich der Ticketstatus in <strong>Lösungsgenehmigung</strong>. Eine E-Mail-Benachrichtigung wird an Sie gesendet.",
      "app_step2_title": "Genehmigen oder Ablehnen",
      "app_step2_desc": "Auf der Ticket-Detailseite können Sie die Lösung als <strong>Genehmigen</strong> oder <strong>Ungenügend, Warten auf Details</strong> markieren.",
      "csat_title": "Zufriedenheitsbewertung (CSAT)",
      "csat_desc": "Nach Abschluss des Tickets können Sie eine Zufriedenheitsbewertung zwischen 1-5 Sternen abgeben. Dieses Feedback trägt zum Lernprozess der KI bei.",
      "tip_csat_title": "Geben Sie 5 Sterne",
      "tip_csat_desc": "5-Sterne-Lösungen werden von der KI als Lernkandidaten markiert und können als automatische Antworten für ähnliche zukünftige Probleme verwendet werden."
    },
    "help.docs.customer.knowledge_base_overview": {
      "title": "Wissensdatenbank",
      "desc": "Die Wissensdatenbank ist das zentrale Gedächtnis des Unternehmens, das Lösungen für häufige Probleme, Anleitungen und technische Dokumente enthält.",
      "search_title": "Durchsuchen der Wissensdatenbank",
      "search_step1_title": "1. Gehen Sie zur Seite der Wissensdatenbank",
      "search_step1_desc": "Klicken Sie im linken Menü auf den Link <strong>Wissensdatenbank</strong>.",
      "search_step2_title": "2. Führen Sie eine Suche durch",
      "search_step2_desc": "Geben Sie Schlüsselwörter in das Suchfeld oben ein. Das System führt eine Volltextsuche in Titeln und Inhalten durch.",
      "search_step3_title": "3. Lesen Sie den Artikel",
      "search_step3_desc": "Klicken Sie auf den entsprechenden Artikel, um zur Schritt-für-Schritt-Lösungsanleitung zu gelangen.",
      "types_title": "Artikeltypen",
      "type1_title": "Wie man",
      "type1_desc": "Schritt-für-Schritt-Bedienungsanleitungen",
      "type2_title": "Fehlerbehebung",
      "type2_desc": "Fehlermeldungen und Lösungen",
      "type3_title": "Referenz",
      "type3_desc": "Technische Spezifikationen und Parameter",
      "type4_title": "Training",
      "type4_desc": "Anleitungen zur Funktionsnutzung",
      "statuses_title": "Artikelstatus",
      "stat1": "Aktiv",
      "stat1_desc": "Genehmigte und aktuelle Artikel",
      "stat2": "Entwurf",
      "stat2_desc": "Unveröffentlichte Inhalte",
      "stat3": "Archiviert",
      "stat3_desc": "Veraltete alte Artikel",
      "tip_ai_title": "Suchen mit KI",
      "tip_ai_desc": "Wenn Sie nicht finden, wonach Sie in der Wissensdatenbank suchen, verwenden Sie den <strong>KI-Assistenten</strong>. Die KI scannt die Wissensdatenbank semantisch und generiert Antworten in einem breiteren Kontext."
    },
    "help.docs.customer.profile_settings": {
      "title": "Profil & Einstellungen",
      "desc": "Aktualisieren Sie Ihre persönlichen Daten, ändern Sie Ihr Passwort und verwalten Sie Ihre Benachrichtigungseinstellungen.",
      "update_title": "Aktualisierung der Profilinformationen",
      "update_step1_title": "1. Gehen Sie zur Profilseite",
      "update_step1_desc": "Klicken Sie unten im linken Menü auf den Link <strong>Mein Profil</strong>.",
      "update_step2_title": "2. Informationen bearbeiten",
      "update_step2_desc": "Sie können Informationen wie Vorname, Nachname, Telefonnummer und Berufsbezeichnung aktualisieren.",
      "update_step3_title": "3. Speichern",
      "update_step3_desc": "Wenden Sie Ihre Änderungen an, indem Sie auf die Schaltfläche <strong>Speichern</strong> klicken.",
      "password_title": "Passwort ändern",
      "pass_item1": "Gehen Sie auf Ihrer Profilseite zum Abschnitt <strong>Passwort ändern</strong>.",
      "pass_item2": "Geben Sie Ihr aktuelles und Ihr neues Passwort ein.",
      "pass_item3": "Ihr neues Passwort muss mindestens 8 Zeichen lang sein.",
      "hotinfo_title": "Systeminfo (Hotinfo)",
      "hotinfo_desc": "Auf Ihrer Profilseite befindet sich Ihre registrierte Systeminformationsdatei (Hotinfo). Diese Datei wird automatisch angehängt, wenn ein Support-Ticket erstellt wird.",
      "hotinfo_item1": "Laden Sie die aus Allplan exportierte <strong>.hxl</strong>-Datei hoch.",
      "hotinfo_item2": "Die Aktualisierung der Systeminformationen beschleunigt den Support-Prozess.",
      "tip_email_title": "Halten Sie Ihre E-Mail-Adresse aktuell",
      "tip_email_desc": "Benachrichtigungen über Support-Tickets und Ankündigungen werden an Ihre registrierte E-Mail-Adresse gesendet. Stellen Sie sicher, dass Ihre E-Mail-Adresse korrekt ist."
    }
  }
};

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] instanceof Object && key in target) {
      Object.assign(source[key], deepMerge(target[key], source[key]));
    }
  }
  Object.assign(target || {}, source);
  return target;
}

function unflatten(data) {
  const result = {};
  for (const key in data) {
    const keys = key.split('.');
    keys.reduce((acc, currentKey, index) => {
      if (index === keys.length - 1) {
        acc[currentKey] = data[key];
      } else {
        acc[currentKey] = acc[currentKey] || {};
      }
      return acc[currentKey];
    }, result);
  }
  return result;
}

for (const locale of locales) {
  const filePath = path.join(basePath, `${locale}.json`);
  const currentContent = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const newTranslations = unflatten(translations[locale]);
  
  const updatedContent = deepMerge(currentContent, newTranslations);
  fs.writeFileSync(filePath, JSON.stringify(updatedContent, null, 2));
  console.log(`Updated ${locale}.json`);
}
