name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    
    # Required for some steps (like database generation)
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/aluplan_support?schema=public"
      JWT_SECRET: "ci_secret"
      JWT_REFRESH_SECRET: "ci_refresh_secret"

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aluplan_support
        ports:
          - 5432:5432
        # Health check to ensure postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
